### ISSUE TITLE
Sidebar becomes footer-bar at mobile browsers

### ISSUE THREAD

**Issue by bigfoot87** [jayj/Japibas#5]
First of all.. thanks for creating this great theme!

I'm really satisfied with the theme on desktop-browsers. But using mobile browsers (Safari, Chrome) on the iPhone and iPad the theme changes. The sidebar moves to the bottom of the webpage and the navigation buttons get replaced by text-links (Next and Previous).. is there anything I can do to change this? :)

**Comment by jayj** [comment]
This was fixed in version 2.0.2 http://wpthemes.jayj.dk/japibas/japibas-2-0-2/
